dependencies:
  GabrielDeTassigny\Blog\Controller\PostViewingController:
    name: GabrielDeTassigny\Blog\Controller\PostViewingController
    dependencies:
      - twig
      - GabrielDeTassigny\Blog\Service\PostViewingService
      - GabrielDeTassigny\Blog\Service\BlogInfoService
      - GabrielDeTassigny\Blog\Service\ExternalLinkService
      - GabrielDeTassigny\Blog\Service\CaptchaService
  GabrielDeTassigny\Blog\Controller\Admin\PostWritingController:
    name: GabrielDeTassigny\Blog\Controller\Admin\PostWritingController
    dependencies:
      - twig
      - GabrielDeTassigny\Blog\Service\Authentication\AdminAuthenticator
      - server_request
      - GabrielDeTassigny\Blog\Service\Publishing\PostWritingService
      - GabrielDeTassigny\Blog\Service\AuthorService
      - GabrielDeTassigny\Blog\Service\Publishing\PostViewingService
  GabrielDeTassigny\Blog\Controller\Admin\ImageController:
    name: GabrielDeTassigny\Blog\Controller\Admin\ImageController
    dependencies:
      - GabrielDeTassigny\Blog\Service\Authentication\AdminAuthenticator
      - server_request
      - json_renderer
      - GabrielDeTassigny\Blog\Service\ImageService
  GabrielDeTassigny\Blog\Controller\AboutPageController:
    name: GabrielDeTassigny\Blog\Controller\AboutPageController
    dependencies:
      - twig
      - GabrielDeTassigny\Blog\Service\BlogInfoService
      - GabrielDeTassigny\Blog\Service\ExternalLinkService
  GabrielDeTassigny\Blog\Controller\Admin\AdminIndexController:
    name: GabrielDeTassigny\Blog\Controller\Admin\AdminIndexController
    dependencies:
      - twig
      - GabrielDeTassigny\Blog\Service\Authentication\AdminAuthenticator
      - GabrielDeTassigny\Blog\Service\Publishing\PostViewingService
      - GabrielDeTassigny\Blog\Service\AuthorService
      - GabrielDeTassigny\Blog\Service\BlogInfoService
      - GabrielDeTassigny\Blog\Service\ExternalLinkService
  GabrielDeTassigny\Blog\Controller\Admin\BlogInfoController:
    name: GabrielDeTassigny\Blog\Controller\Admin\BlogInfoController
    dependencies:
      - twig
      - GabrielDeTassigny\Blog\Service\BlogInfoService
      - GabrielDeTassigny\Blog\Service\Authentication\AdminAuthenticator
      - server_request
  GabrielDeTassigny\Blog\Controller\Admin\ExternalLinkController:
    name: GabrielDeTassigny\Blog\Controller\Admin\ExternalLinkController
    dependencies:
      - GabrielDeTassigny\Blog\Service\Authentication\AdminAuthenticator
      - twig
      - GabrielDeTassigny\Blog\Service\ExternalLinkService
      - server_request
      - GabrielDeTassigny\Blog\Renderer\ErrorRenderer
      - GabrielDeTassigny\Blog\Service\AuthorService
  GabrielDeTassigny\Blog\Controller\Admin\AuthorController:
    name: GabrielDeTassigny\Blog\Controller\Admin\AuthorController
    dependencies:
      - GabrielDeTassigny\Blog\Service\AuthorService
      - GabrielDeTassigny\Blog\Service\Authentication\AdminAuthenticator
      - twig
      - server_request
  GabrielDeTassigny\Blog\Controller\RssController:
    name: GabrielDeTassigny\Blog\Controller\RssController
    dependencies:
      - GabrielDeTassigny\Blog\Service\RssService
      - GabrielDeTassigny\Blog\Renderer\RssRenderer
  GabrielDeTassigny\Blog\Controller\CommentController:
    name: GabrielDeTassigny\Blog\Controller\CommentController
    dependencies:
      - GabrielDeTassigny\Blog\Service\CommentService
      - server_request
      - GabrielDeTassigny\Blog\Renderer\JsonRenderer
      - GabrielDeTassigny\Blog\Service\CaptchaService
  GabrielDeTassigny\Blog\Controller\Admin\CommentAdminController:
    name: GabrielDeTassigny\Blog\Controller\Admin\CommentAdminController
    dependencies:
      - GabrielDeTassigny\Blog\Service\Authentication\AdminAuthenticator
      - twig
      - GabrielDeTassigny\Blog\Service\CommentService
      - server_request

  GabrielDeTassigny\Blog\Service\PostViewingService:
    name: GabrielDeTassigny\Blog\Service\PostViewingService
    dependencies:
      - post_repository

  GabrielDeTassigny\Blog\Service\Authentication\AdminAuthenticator:
    name: GabrielDeTassigny\Blog\Service\Authentication\HttpBasicAuthenticationService
  GabrielDeTassigny\Blog\Service\Publishing\PostWritingService:
    name: GabrielDeTassigny\Blog\Service\Publishing\PostWritingService
    dependencies:
      - entity_manager
      - GabrielDeTassigny\Blog\Service\AuthorService
  GabrielDeTassigny\Blog\Service\ImageService:
    name: GabrielDeTassigny\Blog\Service\ImageService
    dependencies:
      - log
  GabrielDeTassigny\Blog\Service\BlogInfoService:
    name: GabrielDeTassigny\Blog\Service\BlogInfoService
    dependencies:
      - blog_info_repository
      - entity_manager
  GabrielDeTassigny\Blog\Service\ExternalLinkService:
    name: GabrielDeTassigny\Blog\Service\ExternalLinkService
    dependencies:
      - external_link_repository
      - entity_manager
  GabrielDeTassigny\Blog\Service\AuthorService:
    name: GabrielDeTassigny\Blog\Service\AuthorService
    dependencies:
      - author_repository
      - entity_manager
  GabrielDeTassigny\Blog\Service\RssService:
    name: GabrielDeTassigny\Blog\Service\RssService
    dependencies:
      - GabrielDeTassigny\Blog\Service\BlogInfoService
      - GabrielDeTassigny\Blog\Service\PostViewingService
      - server_request
  GabrielDeTassigny\Blog\Service\CommentService:
    name: GabrielDeTassigny\Blog\Service\CommentService
    dependencies:
      - entity_manager
      - GabrielDeTassigny\Blog\Service\PostViewingService
      - comment_repository

  GabrielDeTassigny\Blog\Service\Publishing\PostViewingService:
    name: GabrielDeTassigny\Blog\Service\Publishing\PostViewingService
    dependencies:
      - post_repository

  GabrielDeTassigny\Blog\Renderer\ErrorRenderer:
    name: GabrielDeTassigny\Blog\Renderer\ErrorRenderer
    dependencies:
      - twig
      - GabrielDeTassigny\Blog\Renderer\JsonRenderer

  Gregwar\Captcha\CaptchaBuilder:
    name: Gregwar\Captcha\CaptchaBuilder
