dependencies:
  GabrielDeTassigny\Blog\Service\Authentication\AdminAuthenticator:
    name: GabrielDeTassigny\Blog\Service\Authentication\HttpBasicAuthenticationService

  Gregwar\Captcha\CaptchaBuilder:
    name: Gregwar\Captcha\CaptchaBuilder
