routes:
  /:
    GET:
      controller: post_viewing_controller
      method: index

  # Posts
  /posts/page/{page}:
    GET:
      controller: post_viewing_controller
      method: getPosts
  /posts/{id:\d+}/edit:
    GET:
      controller: post_writing_controller
      method: editPost
  /posts/{id:\d+}/{slug}:
    GET:
      controller: post_viewing_controller
      method: showPost
  /posts/new:
    GET:
      controller: post_writing_controller
      method: newPost
  /posts:
    POST:
      controller: post_writing_controller
      method: createPost
  /posts/{id:\d+}:
    POST:
      controller: post_writing_controller
      method: updatePost
  /posts/{id:\d+}/comments:
    POST:
      controller: comment_controller
      method: createComment
  /comments/captcha:
    GET:
      controller: comment_controller
      method: refreshCaptcha

  # Admin
  /admin:
    GET:
      controller: admin_index_controller
      method: index
  /admin/images/upload:
    POST:
      controller: image_controller
      method: upload
  /about:
    GET:
      controller: about_page_controller
      method: showAboutPage
  /admin/info/edit:
    GET:
      controller: blog_info_controller
      method: edit
  /admin/info/update:
    POST:
      controller: blog_info_controller
      method: update
  /admin/posts/{id:\d+}/comments:
    GET:
      controller: comment_admin_controller
      method: index
    POST:
      controller: comment_admin_controller
      method: createComment
  /admin/posts/{id:\d+}/preview:
    GET:
      controller: post_writing_controller
      method: previewPost
  /admin/comments/{id:\d+}:
    DELETE:
      controller: comment_admin_controller
      method: deleteComment
  /admin/posts/{id:\d+}/comments/new:
    GET:
      controller: comment_admin_controller
      method: newComment
  /external-links/new:
    GET:
      controller: external_link_controller
      method: newExternalLink
  /external-links:
    POST:
      controller: external_link_controller
      method: createExternalLink
  /external-links/{id:\d+}:
    DELETE:
      controller: external_link_controller
      method: deleteExternalLink
  /authors/new:
    GET:
      controller: author_controller
      method: newAuthor
  /authors:
    POST:
      controller: author_controller
      method: createAuthor
  /rss:
    GET:
      controller: rss_controller
      method: showRss
